project:
  type: book
  output-dir: docs

book:
  title: "ThinkR"
  author: "Norah Jones"
  date: "22/03/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - href: td.qmd
      text: TD développement de package
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-overflow: wrap
  pdf:
    documentclass: scrreprt



