project:
  type: book
  output-dir: docs

format:
  html:
    #callout-appearance: simple
    theme:
      light:
        - cosmo
        - css/callout.css
    lang: "fr"
    cover-image: images/Rlogo.png
    code-link: true
    code-overflow: wrap
  pdf:
    documentclass: scrreprt

book:
  title: "Développement de packages"
  author:
    - name: Alain Corvisier
      email: alain.corvisier@proton.me
      url: https://a-lambda.github.io
      affiliation: CPAM des FLANDRES
  date: last-modified
  #open-graph: true
  chapters:
    - href: index.qmd
    - part: "TD"
      chapters:
        - href: 01-unit_tests.qmd
        - href: 02-package_doc.qmd
        - href: 03-restart.qmd
        - href: 04-data.qmd
        - href: 05-check.qmd
        - href: 06-versioning.qmd
        - href: 07-check_param.qmd
        - href: 08-first_merge_requests.qmd
        - href: 09-dots.qmd
        - href: 10-advanced_doc.qmd
        - href: 11-tidyeval.qmd
        - href: 12-purrr.qmd
  appendices:
    - href: procedure_package_fusen.qmd
      text: "Créer un package R avec {fusen}"

    # - references.qmd

bibliography: references.bib





