project:
  type: book
  output-dir: docs

book:
  title: "TD - Développement de packages"
  author: "anonymous"
  date: "22/03/2024"
  chapters:
    - href: index.qmd
      text: Préface
    - intro.qmd
    - href: 01-unit_tests.qmd
      text: Tests unitaires
    - href: 02-package_doc.qmd
      text: Documentation du package
    - href: 03-restart.qmd
      text: Et si on recommençait ?
    - href: 04-data.qmd
      text: Données
    - href: 05-check.qmd
      text: Check
    - href: 06-versioning.qmd
      text: Versionnement
    - href: 07-check_param.qmd
      text: Vérification des paramètres
    - href: 08_first_merge_requests.qmd
      text: Premières Merge Requests
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    lang: "fr"
    cover-image: images/thinkr-logo.png
    code-link: true
    code-overflow: wrap
  pdf:
    documentclass: scrreprt



